# Generated by Django 5.0.3 on 2024-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
