# Generated by Django 5.0.3 on 2024-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_appointment_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motto", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=200)),
                ("long_description", models.TextField()),
                ("full_description", models.TextField()),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("9-10", "9:00 AM - 10:00 AM"),
                    ("10-11", "10:00 AM - 11:00 AM"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
