# Generated by Django 5.0.3 on 2024-03-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_personalinformation_alter_appointment_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinformation",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
