# Generated by Django 5.0.3 on 2024-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_personalinformation_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="location",
            field=models.TextField(null=True),
        ),
    ]
