# Generated by Django 5.0.3 on 2024-03-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_personalinformation_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinformation",
            name="full_description",
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="full_description_First_Pera",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="full_description_Second_Pera",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="full_description_Third_Pera",
            field=models.TextField(null=True),
        ),
    ]
