# Generated by Django 5.0.3 on 2024-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="Client_Name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="Profession",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
