# Generated by Django 5.0.3 on 2024-03-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("9-10", "9:00 AM - 10:00 AM"),
                    ("10-11", "10:00 AM - 11:00 AM"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="AvailableTime",
        ),
    ]
