# Generated by Django 5.0.3 on 2024-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_availabletime_alter_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabletime",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=20,
            ),
        ),
    ]
