# Generated by Django 5.0.3 on 2024-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_availabletime_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinformation",
            name="about_us_image",
            field=models.ImageField(blank=True, null=True, upload_to="about_us_images"),
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
