# Generated by Django 5.0.3 on 2024-03-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_personalinformation_about_us_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonalInformation",
            new_name="SiteDescription",
        ),
    ]
