# Generated by Django 5.0.3 on 2024-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_rename_personalinformation_sitedescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedescription",
            name="availabe_times",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
