# Generated by Django 5.0.3 on 2024-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_sitedescription_availabe_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedescription",
            name="availabe_times",
            field=models.TextField(null=True),
        ),
    ]
