# Generated by Django 5.0.3 on 2024-03-29 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_sitedescription_availabe_times"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="concerns",
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="pdf_document",
            field=models.FileField(blank=True, null=True, upload_to="pdf_documents/"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
