# Generated by Django 5.0.3 on 2024-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_remove_appointment_time_appointment_concerns_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_logos/"
                    ),
                ),
            ],
        ),
    ]
