# Generated by Django 5.0.3 on 2024-03-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="concerns",
            new_name="cause",
        ),
    ]
