# Generated by Django 5.0.3 on 2024-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_sitedescription_first_banner_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedescription",
            name="bkash_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sitedescription",
            name="bkash_transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitedescription",
            name="nagad_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sitedescription",
            name="nagad_transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitedescription",
            name="rocket_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sitedescription",
            name="rocket_transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
