# Generated by Django 5.0.3 on 2024-04-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_sitedescription_bkash_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitedescription",
            old_name="bkash_phone",
            new_name="bkash_phone_No",
        ),
        migrations.RenameField(
            model_name="sitedescription",
            old_name="nagad_phone",
            new_name="nagad_phone_No",
        ),
        migrations.RenameField(
            model_name="sitedescription",
            old_name="rocket_phone",
            new_name="rocket_phone_No",
        ),
    ]
