# Generated by Django 5.0.4 on 2024-04-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_delete_availabletime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitedescription",
            name="motto",
        ),
        migrations.RemoveField(
            model_name="sitedescription",
            name="short_description",
        ),
    ]
